
// This file has been generated by the GUI designer. Do not modify.
namespace AccessControl
{
	public partial class frmInfo
	{
		private global::Gtk.VBox vbox3;
		private global::Gtk.VBox vbox5;
		private global::Gtk.Fixed fixed3;
		private global::Gtk.Label lb1;
		private global::Gtk.Label D1;
		private global::Gtk.Label lb2;
		private global::Gtk.Label D2;
		private global::Gtk.Label lb3;
		private global::Gtk.Label D3;
		private global::Gtk.Label lb4;
		private global::Gtk.Label D4;
		private global::Gtk.Label lb5;
		private global::Gtk.Label D5;
		private global::Gtk.Label lb6;
		private global::Gtk.Label D6;
		private global::Gtk.Label lb7;
		private global::Gtk.Label D7;
		private global::Gtk.Label lb8;
		private global::Gtk.Label D8;
		private global::Gtk.Label lb9;
		private global::Gtk.Label D9;
		private global::Gtk.Label lb10;
		private global::Gtk.Label D10;
		private global::Gtk.Label lb11;
		private global::Gtk.Label D11;
		private global::Gtk.Label lb12;
		private global::Gtk.Label D12;
		private global::Gtk.Label lb13;
		private global::Gtk.Label D13;
		private global::Gtk.Button btnExit;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget AccessControl.frmInfo
			this.Name = "AccessControl.frmInfo";
			this.Title = global::Mono.Unix.Catalog.GetString ("Información del sistema");
			this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-dialog-info", global::Gtk.IconSize.Menu);
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child AccessControl.frmInfo.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.fixed3 = new global::Gtk.Fixed ();
			this.fixed3.Name = "fixed3";
			this.fixed3.HasWindow = false;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.lb1 = new global::Gtk.Label ();
			this.lb1.Name = "lb1";
			this.lb1.LabelProp = global::Mono.Unix.Catalog.GetString ("Versión:");
			this.fixed3.Add (this.lb1);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.lb1]));
			w1.X = 10;
			w1.Y = 5;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.D1 = new global::Gtk.Label ();
			this.D1.Name = "D1";
			this.D1.LabelProp = global::Mono.Unix.Catalog.GetString ("...");
			this.fixed3.Add (this.D1);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.D1]));
			w2.X = 180;
			w2.Y = 5;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.lb2 = new global::Gtk.Label ();
			this.lb2.Name = "lb2";
			this.lb2.LabelProp = global::Mono.Unix.Catalog.GetString ("Fecha de la versión:");
			this.fixed3.Add (this.lb2);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.lb2]));
			w3.X = 10;
			w3.Y = 25;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.D2 = new global::Gtk.Label ();
			this.D2.Name = "D2";
			this.D2.LabelProp = global::Mono.Unix.Catalog.GetString ("...");
			this.fixed3.Add (this.D2);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.D2]));
			w4.X = 180;
			w4.Y = 25;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.lb3 = new global::Gtk.Label ();
			this.lb3.Name = "lb3";
			this.lb3.LabelProp = global::Mono.Unix.Catalog.GetString ("Cadena de conexión:");
			this.fixed3.Add (this.lb3);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.lb3]));
			w5.X = 10;
			w5.Y = 45;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.D3 = new global::Gtk.Label ();
			this.D3.Name = "D3";
			this.D3.LabelProp = global::Mono.Unix.Catalog.GetString ("...");
			this.fixed3.Add (this.D3);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.D3]));
			w6.X = 180;
			w6.Y = 45;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.lb4 = new global::Gtk.Label ();
			this.lb4.Name = "lb4";
			this.lb4.LabelProp = global::Mono.Unix.Catalog.GetString ("Nombre dispositivo:");
			this.fixed3.Add (this.lb4);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.lb4]));
			w7.X = 10;
			w7.Y = 65;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.D4 = new global::Gtk.Label ();
			this.D4.Name = "D4";
			this.D4.LabelProp = global::Mono.Unix.Catalog.GetString ("...");
			this.fixed3.Add (this.D4);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.D4]));
			w8.X = 180;
			w8.Y = 65;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.lb5 = new global::Gtk.Label ();
			this.lb5.Name = "lb5";
			this.lb5.LabelProp = global::Mono.Unix.Catalog.GetString ("Usuario del dispositivo:");
			this.fixed3.Add (this.lb5);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.lb5]));
			w9.X = 10;
			w9.Y = 85;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.D5 = new global::Gtk.Label ();
			this.D5.Name = "D5";
			this.D5.LabelProp = global::Mono.Unix.Catalog.GetString ("...");
			this.fixed3.Add (this.D5);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.D5]));
			w10.X = 180;
			w10.Y = 85;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.lb6 = new global::Gtk.Label ();
			this.lb6.Name = "lb6";
			this.lb6.LabelProp = global::Mono.Unix.Catalog.GetString ("HostName:");
			this.fixed3.Add (this.lb6);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.lb6]));
			w11.X = 10;
			w11.Y = 105;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.D6 = new global::Gtk.Label ();
			this.D6.Name = "D6";
			this.D6.LabelProp = global::Mono.Unix.Catalog.GetString ("...");
			this.fixed3.Add (this.D6);
			global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.D6]));
			w12.X = 180;
			w12.Y = 105;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.lb7 = new global::Gtk.Label ();
			this.lb7.Name = "lb7";
			this.lb7.LabelProp = global::Mono.Unix.Catalog.GetString ("DomainName:");
			this.fixed3.Add (this.lb7);
			global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.lb7]));
			w13.X = 10;
			w13.Y = 125;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.D7 = new global::Gtk.Label ();
			this.D7.Name = "D7";
			this.D7.LabelProp = global::Mono.Unix.Catalog.GetString ("...");
			this.fixed3.Add (this.D7);
			global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.D7]));
			w14.X = 180;
			w14.Y = 125;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.lb8 = new global::Gtk.Label ();
			this.lb8.Name = "lb8";
			this.lb8.LabelProp = global::Mono.Unix.Catalog.GetString ("IP (1):");
			this.fixed3.Add (this.lb8);
			global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.lb8]));
			w15.X = 10;
			w15.Y = 145;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.D8 = new global::Gtk.Label ();
			this.D8.Name = "D8";
			this.D8.LabelProp = global::Mono.Unix.Catalog.GetString ("...");
			this.fixed3.Add (this.D8);
			global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.D8]));
			w16.X = 180;
			w16.Y = 145;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.lb9 = new global::Gtk.Label ();
			this.lb9.Name = "lb9";
			this.lb9.LabelProp = global::Mono.Unix.Catalog.GetString ("IP (2):");
			this.fixed3.Add (this.lb9);
			global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.lb9]));
			w17.X = 10;
			w17.Y = 165;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.D9 = new global::Gtk.Label ();
			this.D9.Name = "D9";
			this.D9.LabelProp = global::Mono.Unix.Catalog.GetString ("...");
			this.fixed3.Add (this.D9);
			global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.D9]));
			w18.X = 180;
			w18.Y = 165;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.lb10 = new global::Gtk.Label ();
			this.lb10.Name = "lb10";
			this.lb10.LabelProp = global::Mono.Unix.Catalog.GetString ("IP (3):");
			this.fixed3.Add (this.lb10);
			global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.lb10]));
			w19.X = 10;
			w19.Y = 185;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.D10 = new global::Gtk.Label ();
			this.D10.Name = "D10";
			this.D10.LabelProp = global::Mono.Unix.Catalog.GetString ("...");
			this.fixed3.Add (this.D10);
			global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.D10]));
			w20.X = 180;
			w20.Y = 185;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.lb11 = new global::Gtk.Label ();
			this.lb11.Name = "lb11";
			this.lb11.LabelProp = global::Mono.Unix.Catalog.GetString ("MAC (1):");
			this.fixed3.Add (this.lb11);
			global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.lb11]));
			w21.X = 10;
			w21.Y = 205;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.D11 = new global::Gtk.Label ();
			this.D11.Name = "D11";
			this.D11.LabelProp = global::Mono.Unix.Catalog.GetString ("...");
			this.fixed3.Add (this.D11);
			global::Gtk.Fixed.FixedChild w22 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.D11]));
			w22.X = 180;
			w22.Y = 205;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.lb12 = new global::Gtk.Label ();
			this.lb12.Name = "lb12";
			this.lb12.LabelProp = global::Mono.Unix.Catalog.GetString ("MAC (2):");
			this.fixed3.Add (this.lb12);
			global::Gtk.Fixed.FixedChild w23 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.lb12]));
			w23.X = 10;
			w23.Y = 225;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.D12 = new global::Gtk.Label ();
			this.D12.Name = "D12";
			this.D12.LabelProp = global::Mono.Unix.Catalog.GetString ("...");
			this.fixed3.Add (this.D12);
			global::Gtk.Fixed.FixedChild w24 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.D12]));
			w24.X = 180;
			w24.Y = 225;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.lb13 = new global::Gtk.Label ();
			this.lb13.Name = "lb13";
			this.lb13.LabelProp = global::Mono.Unix.Catalog.GetString ("MAC (3):");
			this.fixed3.Add (this.lb13);
			global::Gtk.Fixed.FixedChild w25 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.lb13]));
			w25.X = 10;
			w25.Y = 245;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.D13 = new global::Gtk.Label ();
			this.D13.Name = "D13";
			this.D13.LabelProp = global::Mono.Unix.Catalog.GetString ("...");
			this.fixed3.Add (this.D13);
			global::Gtk.Fixed.FixedChild w26 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.D13]));
			w26.X = 180;
			w26.Y = 245;
			this.vbox5.Add (this.fixed3);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.fixed3]));
			w27.Position = 0;
			w27.Expand = false;
			w27.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.btnExit = new global::Gtk.Button ();
			this.btnExit.HeightRequest = 80;
			this.btnExit.CanFocus = true;
			this.btnExit.Name = "btnExit";
			this.btnExit.UseUnderline = true;
			// Container child btnExit.Gtk.Container+ContainerChild
			global::Gtk.Alignment w28 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w29 = new global::Gtk.HBox ();
			w29.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w30 = new global::Gtk.Image ();
			w30.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-quit", global::Gtk.IconSize.Menu);
			w29.Add (w30);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w32 = new global::Gtk.Label ();
			w32.LabelProp = global::Mono.Unix.Catalog.GetString ("  Salir");
			w32.UseUnderline = true;
			w29.Add (w32);
			w28.Add (w29);
			this.btnExit.Add (w28);
			this.vbox5.Add (this.btnExit);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.btnExit]));
			w36.Position = 1;
			w36.Expand = false;
			w36.Fill = false;
			this.vbox3.Add (this.vbox5);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.vbox5]));
			w37.Position = 0;
			w37.Expand = false;
			w37.Fill = false;
			this.Add (this.vbox3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 352;
			this.Show ();
			this.btnExit.Clicked += new global::System.EventHandler (this.OnBtnExitClicked);
		}
	}
}
