
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action HerramientasAction;
	private global::Gtk.Action AyudaAction;
	private global::Gtk.Action InformacinDelSistemaAction;
	private global::Gtk.Action InformacinDeLaBaseDeDatosAction;
	private global::Gtk.VBox vbox1;
	private global::Gtk.MenuBar menubar1;
	private global::Gtk.DrawingArea drawingarea1;
	private global::Gtk.TextView InfoText;
	private global::Gtk.HBox hbox1;
	private global::Gtk.Button button1;
	private global::Gtk.Button button2;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.HerramientasAction = new global::Gtk.Action ("HerramientasAction", global::Mono.Unix.Catalog.GetString ("Herramientas"), null, null);
		this.HerramientasAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Herramientas");
		w1.Add (this.HerramientasAction, null);
		this.AyudaAction = new global::Gtk.Action ("AyudaAction", global::Mono.Unix.Catalog.GetString ("Ayuda"), null, null);
		this.AyudaAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Ayuda");
		w1.Add (this.AyudaAction, null);
		this.InformacinDelSistemaAction = new global::Gtk.Action ("InformacinDelSistemaAction", global::Mono.Unix.Catalog.GetString ("Información del sistema"), null, null);
		this.InformacinDelSistemaAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Información del sistema");
		w1.Add (this.InformacinDelSistemaAction, null);
		this.InformacinDeLaBaseDeDatosAction = new global::Gtk.Action ("InformacinDeLaBaseDeDatosAction", global::Mono.Unix.Catalog.GetString ("Información de la base de datos"), null, null);
		this.InformacinDeLaBaseDeDatosAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Información de la base de datos");
		w1.Add (this.InformacinDeLaBaseDeDatosAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='HerramientasAction' action='HerramientasAction'/><menu name='AyudaAction' action='AyudaAction'><menuitem name='InformacinDelSistemaAction' action='InformacinDelSistemaAction'/><menuitem name='InformacinDeLaBaseDeDatosAction' action='InformacinDeLaBaseDeDatosAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.drawingarea1 = new global::Gtk.DrawingArea ();
		this.drawingarea1.Name = "drawingarea1";
		this.vbox1.Add (this.drawingarea1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.drawingarea1]));
		w3.Position = 1;
		// Container child vbox1.Gtk.Box+BoxChild
		this.InfoText = new global::Gtk.TextView ();
		this.InfoText.Buffer.Text = "...";
		this.InfoText.CanFocus = true;
		this.InfoText.Name = "InfoText";
		this.vbox1.Add (this.InfoText);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.InfoText]));
		w4.Position = 2;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.button1 = new global::Gtk.Button ();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.hbox1.Add (this.button1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button1]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.button2 = new global::Gtk.Button ();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.hbox1.Add (this.button2);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button2]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w7.Position = 3;
		w7.Expand = false;
		w7.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 474;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.InformacinDelSistemaAction.Activated += new global::System.EventHandler (this.OnInformacinDelSistemaActionActivated);
		this.InformacinDeLaBaseDeDatosAction.Activated += new global::System.EventHandler (this.OnInformacinDeLaBaseDeDatosActionActivated);
		this.button2.Clicked += new global::System.EventHandler (this.OnButton2Clicked);
	}
}
